// vue-client/src/views/identity/Register.vue
<template>
    <h1>Register</h1>

<div class="row">
    <div class="col-md-4">
            <h4>Create a new account.</h4>
            <hr />
            <div class="text-danger validation-summary-valid" data-valmsg-summary="true"><ul><li style="display:none"></li>
</ul></div>
            <div class="form-group">
                <label for="Input_Email">Email</label>
                <input v-model="email" class="form-control" type="email" data-val="true" data-val-email="The Email field is not a valid e-mail address." data-val-required="The Email field is required." id="Input_Email" name="Input.Email" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Input.Email" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group">
                <label for="Input_Password">Password</label>
                <input v-model="password" class="form-control" type="password" data-val="true" data-val-length="The field Password must be a string with a minimum length of 6 and a maximum length of 100." data-val-length-max="100" data-val-length-min="6" data-val-required="The Password field is required." id="Input_Password" maxlength="100" name="Input.Password" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Input.Password" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group">
                <label for="Input_ConfirmPassword">Confirm Password</label>
                <input class="form-control" type="password" data-val="true" data-val-equalto="The password and confirmation password do not match." data-val-equalto-other="*.Password" id="Input_ConfirmPassword" name="Input.ConfirmPassword" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Input.ConfirmPassword" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group">
                <label for="Input_FirstName">First Name</label>
                <input v-model="firstName" class="form-control" type="text" data-val="true" data-val-length="The field First Name must be a string with a minimum length of 1 and a maximum length of 128." data-val-length-max="128" data-val-length-min="1" data-val-maxlength="The field First Name must be a string or array type with a maximum length of &#x27;128&#x27;." data-val-maxlength-max="128" data-val-required="The First Name field is required." id="Input_FirstName" maxlength="128" name="Input.FirstName" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Input.FirstName" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group">
                <label for="Input_LastName">Last Name</label>
                <input v-model="lastName" class="form-control" type="text" data-val="true" data-val-length="The field Last Name must be a string with a minimum length of 1 and a maximum length of 128." data-val-length-max="128" data-val-length-min="1" data-val-maxlength="The field Last Name must be a string or array type with a maximum length of &#x27;128&#x27;." data-val-maxlength-max="128" data-val-required="The Last Name field is required." id="Input_LastName" maxlength="128" name="Input.LastName" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Input.LastName" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group">
                <label for="Input_UserLevel">User level</label>
                <input v-model="userlevel" class="form-control" type="text" data-val="true" data-val-length="The field User level must be a string with a minimum length of 1 and a maximum length of 2." data-val-length-max="2" data-val-length-min="1" data-val-maxlength="The field User level must be a string or array type with a maximum length of &#x27;1&#x27;." data-val-maxlength-max="1" data-val-required="The User level field is required." id="Input_UserLevel" maxlength="1" name="Input.UserLevel"/>
                <span class="text-danger field-validation-valid" data-valmsg-for="Input.UserLevel" data-valmsg-replace="true"></span>
            </div>
            <button @click="registerClicked($event)" type="submit" class="btn btn-primary">Register</button>
        <input name="__RequestVerificationToken" type="hidden" value="CfDJ8E7aXoJBzExOsnhqYuBQ2ooCgouXHApxEaG_G1GK47Lm-DfA6vS99WVP9b_aCM5XkKDo2KPTPLNETTGCA1ixFjJKBiffupX6yOaBVokx-xStflGtgo1Q9aZUT7ZsXPAa1jFHybX43uYalLXvCP-3K0A" />
    </div>
    <div class="col-md-6 col-md-offset-2">
    </div>
</div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import router from "vue-router";

@Options({
    components: {},
    props: {},
})
export default class Register extends Vue {
    email: string = "";
    password: string = "";
    firstname: string = "";
    lastname: string = "";
    userlevel: string = "";

    async registerClicked(event: Event): Promise<void> {
        console.log(this.email, this.password, event);

        store
            .dispatch("register", { email: this.email, password: this.password, firstname: this.firstname, lastname: this.lastname, userlevel: this.userlevel })
            .then(() => {
                if (store.state.token != null) {
                    this.$router.push("/");
                }
            });
    }
}
</script>

// react-client/src/containers/identity/Register.tsx
import React, { useContext, useState } from "react";
import { Redirect } from "react-router";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";

const Register = () => {
    const appState = useContext(AppContext);

    const [registerData, setRegisterData] = useState({ email: '', password: '', firstname: '', lastname: '', userlevel: ''});
    const [alertMessage, setAlertMessage] = useState('');

    const registerClicked = async (e: Event) => {
        e.preventDefault();
        if (registerData.email === '' || registerData.password === '' || registerData.firstname === '' || registerData.lastname === '' || registerData.userlevel === '') {
            setAlertMessage('Empty email or pawwsord!');
        };
        setAlertMessage('');
        let response = await IdentityService.Register('account/register', registerData);
        if (!response.ok) {
            setAlertMessage(response.messages![0]);
        } else {
            setAlertMessage('');
            appState.jwt = response.data!.token;
            appState.firstName = response.data!.firstname;
            appState.lastName = response.data!.lastname;
            appState.setAuthInfo(response.data!.token, response.data!.firstname, response.data!.lastname);
        }
    }

    return (
        <>
            { appState.jwt !== null ? <Redirect to="/" /> : null}
            <h1>Register</h1>
            <form onSubmit={(e) => registerClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="Input_Email">Email</label>
                                <input value={registerData.email} onChange={e => setRegisterData({ ...registerData, email: e.target.value })} className="form-control" type="email" id="Input_Email" name="Input.Email" placeholder="user@example.com"  autoComplete="username" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Password">Password</label>
                                <input value={registerData.password} onChange={e => setRegisterData({ ...registerData, password: e.target.value })} className="form-control" type="password" id="Input_Password" name="Input.Password" placeholder="Input your current password..." autoComplete="current-password" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Firstname">First Name</label>
                                <input value={registerData.firstname} onChange={e => setRegisterData({ ...registerData, firstname: e.target.value })} className="form-control" type="firstname" id="Input_Firstname" name="Input.Firstname" placeholder="Input your first name..." autoComplete="firstname" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Lastname">Last Name</label>
                                <input value={registerData.lastname} onChange={e => setRegisterData({ ...registerData, lastname: e.target.value })} className="form-control" type="lastname" id="Input_Lastname" name="Input.Lastname" placeholder="Input your last name..." autoComplete="lastname" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Userlevel">User Level</label>
                                <input value={registerData.userlevel} onChange={e => setRegisterData({ ...registerData, userlevel: e.target.value })} className="form-control" type="userlevel" id="Input_Userlevel" name="Input.Userlevel" placeholder="Input your user level..." autoComplete="userlevel" />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => registerClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Register</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
}

export default Register;
